package org.openmrs.module.drools.rules.labtests;

import org.openmrs.Patient;
import org.openmrs.module.drools.calculation.Operator;
import static org.openmrs.module.drools.utils.DroolsDateUtils.yearsAgo;
import org.openmrs.module.patientflags.PatientFlag
import org.openmrs.Order;
import java.util.List;


rule "Reduced Kidney Function"
    agenda-group "ReducedKidneyFunction"
    salience 10
    when
        $patient: Patient()
        eval(!hasCondition3($patient, "CIEL:145438"))
        eval(handleKidneyDisease($patient,"CIEL:790", 0.0, 45.0))
    then
        insert(new PatientFlag(
                                  $patient,
                                  null,
                                  "Reduced kidney function detected (eGFR < 45)"
                              ));
end

rule "Chronic Kidney Disease"
    agenda-group "ChronicKidneyDisease"
    salience 0
    when
        $patient: Patient()
        eval(handleKidneyDisease($patient,"CIEL:790", 45.0, 60.0))
    then
        insert(new PatientFlag(
                                  $patient,
                                  null,
                                  "eGFR <60 on two occasions three months apart, suspect Chronic Kidney Disease (CKD)."
                              ));
end