package org.openmrs.module.drools.rules.labtests;

import org.openmrs.Patient;
import org.openmrs.Concept;
import org.openmrs.Condition;
import org.openmrs.Order;
import org.openmrs.Obs;
import org.openmrs.api.context.Context;
import org.openmrs.module.drools.calculation.CalculationUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.*;
import static org.openmrs.module.drools.calculation.CalculationUtils.splitValues;


declare PatientRecommendation3
    title : String
    recommendation: String
end

function boolean hasCondition3(Patient patient, String conditionRef) {
    Concept concept = CalculationUtils.getConcept(conditionRef);
    return Context.getConditionService().getActiveConditions(patient).stream().anyMatch(condition -> condition.getCondition().getCoded() != null && condition.getCondition().getCoded().equals(concept));
}

function boolean handleKidneyDisease(Patient patient, String conditionRef, Double lowMargin, Double highMargin) {
      Concept concept = CalculationUtils.getConcept(conditionRef);
      java.util.List<Obs> obsSubList = new ArrayList<Obs>();

      List<Obs> obsList = Context.getObsService().getObservationsByPersonAndConcept(patient,concept);
                  for (int i = 0; i < obsList.size(); i++) {
                   Double eGFR = calculate_eGFR(patient.getGender(), patient.getAge(), obsList.get(i).getValueNumeric());


                  System.out.println("eGFR => " + eGFR);

                   if (eGFR < 60) {
                         for (int j = i + 1; j < obsList.size(); j++) {
                              Double eGFR2 = calculate_eGFR(patient.getGender(), patient.getAge(), obsList.get(j).getValueNumeric());
                              long differenceInMonths = differenceDates(obsList.get(i).getObsDatetime(), obsList.get(j).getObsDatetime(), "MONTHS");

                              System.out.println("eGFR2 => " + eGFR2);

                               if(eGFR2 < 60 && differenceInMonths <= 3)
                                  return (lowMargin <= eGFR &&  eGFR < highMargin) || (lowMargin <= eGFR2 && eGFR2 < highMargin);

                         }
                   }
        }


     return false;
}

function long differenceDates(Date date1, Date date2, String type){
    long diffMs = date1.getTime() - date2.getTime();
    long diffDays = diffMs / (1000 * 60 * 60 * 24);
    if(type == "DAYS")
        return diffDays;
    return diffDays / 30;
}


function Double calculate_eGFR(String gender, Integer ageYears, Double serumCreatinineValue) {

		return (Objects.equals(gender, "F") ?

		142 * Math.pow(Math.min(serumCreatinineValue / 0.7, 1), -0.241)
		        * Math.pow(Math.max(serumCreatinineValue / 0.7, 1), -1.200) * Math.pow(0.9938, ageYears) * 1.012 : 142
		        * Math.pow(Math.min(serumCreatinineValue / 0.9, 1), -0.302)
		        * Math.pow(Math.max(serumCreatinineValue / 0.9, 1), -1.200) * Math.pow(0.9938, ageYears));
}

